# Generated by Django 5.1.3 on 2024-11-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loan_loan_id_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
