# Generated by Django 5.1.3 on 2024-11-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='id',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
